### PR TITLE
fix: invalid memory address due to store is nil in gitcreds.go

### PR DESCRIPTION
**Pull request by pasha-codefresh**
Closes: https://github.com/argoproj-labs/argocd-image-updater/issues/621

### CODE REVIEW

**Review by jannfis — CHANGES_REQUESTED** [review]
I believe we need to update the Git client in `ext/git` first.

**Review by jannfis — APPROVED** [review]
As discussed with @pasha-codefresh, this seems to unblock most people.

Update of ext/git will be targeted for 0.14

LGTM.

**Comment by pasha-codefresh** [comment]
@jannfis it is not crashing anymore ( master branch it is another issue )

**Comment by pasha-codefresh** [comment]
Снимок экрана 2024-05-27 в 19 37 38

**Pull request merged**
