### PR TITLE
feat: Support OCI repositories by using distribution/v3

### PR DESCRIPTION
**Pull request by ludovicMercier**
Implement [distribution/v3](https://github.com/distribution/distribution/V3) which is the last version of [docker/distribution](https://github.com/docker/distribution) and support oci manisfest  to solve #236

### CODE REVIEW

**Comment by jannfis** [comment]
Thanks for this PR, @ludovicMercier!

Please allow me some time for proper review - it's a quite complex change.

**Comment by ludovicMercier** [comment]
Hi @jannfis,
I agree with you, take the time you need on the review.

**Comment by jannfis** [comment]
@ludovicMercier I gave this PR some quick tests, and it worked great so far! I could even observe some performance improvements in contrast to using the (pretty old) `docker-registry-client` library. 

I adapted my local checkout of your PR's branch to include latest changes in `master` branch, do you mind if I push them back to your PR's branch (or send a PR to your fork)?

I think it's good to merge, I just have a couple of tests in queue to perform either tomorrow or on the weekend. 

Thank you! I really appreciate this contribution.

**Comment by ludovicMercier** [comment]
Hi @jannfis,
You merge directly in this PR it's ok to me.
If i see someting else where i can help i'll rebase my fork to stay updated with the project.

**Pull request merged**
