### PR TITLE
feat: Allow reuse of Argo CD repo credentials

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

Closes https://github.com/argoproj-labs/argocd-image-updater/issues/138

PR implements proposal described in https://github.com/argoproj-labs/argocd-image-updater/issues/138 . The default credentials source is "repocreds" since it requires no configuration.

### CODE REVIEW

**Review by jannfis — APPROVED** [review]
LGTM - awesome, thank you @alexmt !

**Comment by diranged** [comment]
@jannfis @alexmt ,
  How would this play with https://github.com/argoproj/argo-cd/pull/5355?

**Comment by alexmt** [comment]
Good point @diranged . We already had a discussion about re-using argocd repo server  to communicate with Git. The downside of that approach is that repo server would get API which is not used by Argo CD itself. 

Image updater already imports Argo CD as a library. So may be we just contribute new Git client methods back to Argo CD? In this case we will get github apps support and future features transparently. 

What do you think @jannfis ?

**Comment by diranged** [comment]
I like currently how the image updater is just working along side argo and using native kubernetes calls for everything. If the argocd application controller is going to be responsible for being aware of the ".argocd-<app>.yaml" files anyways, perhaps thats where the responsibility should lie to push changes back into a repository based on the status of an Application resource?

The benefit is that _any_ Application customization or override can then be passed back into the Git repository as-code if the operators choose to do that... which would actually be a great win for our development environment where we want to enable developers to make changes to the Application objects directly, but are also afraid of configuration drift from what's in-code vs what is in-cluster.

**Pull request merged**
