### PR TITLE
fix: #896 App of apps being overwritten by image-updater

### PR DESCRIPTION
**Pull request by chengfang**
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/896

### CODE REVIEW

**Comment by chengfang** [comment]
the real changes are captured in the screenshot below. `findApplicationByName` function is deleted and inlined into `GetApplication`, and the element type of `matchedApps` is changed from pointer to `Application`.

Screenshot 2024-11-06 at 8 49 52 AM

**Review by fletch3555 — APPROVED** [review]
LGTM!

**Review by jannfis — APPROVED** [review]
LGTM

**Comment by jannfis** [comment]
We should put out a 0.15.1 with this fix asap.

**Comment by chengfang** [comment]
thanks @jannfis . I'll cherry-pick bug fixes to release-0.15 branch and work on the v0.15.1. https://issues.redhat.com/browse/GITOPS-5813

**Pull request merged**
