### PR TITLE
:test_tube: adds manifest tests

### LINKED ISSUE #752: Add tests to validate manifests against schemas
We should have tests to validate all kubernetes and kustomize manifest yaml files. If they contain errors like unexpected field names, it can be caught by tests.  For example, the errors fixed in PR #750

### PR DESCRIPTION
**Pull request by bpsoos**
resolves #752

This PR adds a make target `test-manifests` that runs a [kubeconform](https://github.com/yannh/kubeconform)  based test to validate the kubernetes/kustomize manifests against their schemas.

### CODE REVIEW

**Comment by chengfang** [comment]
How about running the script directly in github actions workflow, without building or running images? For local run, we can require users to install kubeconform before running.

Can you also share some negative test results?

**Comment by bpsoos** [comment]
@chengfang Negative tests results:
```
docker run --rm \
		-v `pwd`/manifests:/home/manifests \
		-v `pwd`/scripts:/home/scripts \
		manifest-tester-argocd-image-updater \
		scripts/test_manifests.sh
/home/manifests/base/config/argocd-image-updater-cm.yaml - ConfigMap argocd-image-updater-config is valid
/home/manifests/base/config/argocd-image-updater-ssh-config.yaml - ConfigMap argocd-image-updater-ssh-config is valid
/home/manifests/base/config/argocd-image-updater-secret.yaml - Secret argocd-image-updater-secret is valid
/home/manifests/base/deployment/kustomization.yaml - Kustomization  is valid
/home/manifests/base/kustomization.yaml - Kustomization  is valid
/home/manifests/base/config/kustomization.yaml - Kustomization  is valid
/home/manifests/base/deployment/argocd-image-updater-deployment.yaml - Deployment argocd-image-updater is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json#/properties/spec/required: missing properties: 'selector'
/home/manifests/base/rbac/kustomization.yaml - Kustomization  is valid
/home/manifests/base/rbac/argocd-image-updater-rolebinding.yaml - RoleBinding argocd-image-updater is valid
/home/manifests/base/rbac/argocd-image-updater-role.yaml - Role argocd-image-updater is valid
/home/manifests/install.yaml - RoleBinding argocd-image-updater is valid
/home/manifests/install.yaml - ConfigMap argocd-image-updater-config is valid
/home/manifests/install.yaml - ConfigMap argocd-image-updater-ssh-config is valid
/home/manifests/install.yaml - Secret argocd-image-updater-secret is valid
/home/manifests/install.yaml - failed validation: error unmarshalling resource: error converting YAML to JSON: yaml: line 158: mapping values are not allowed in this context
/home/manifests/install.yaml - Role argocd-image-updater is valid
/home/manifests/base/rbac/argocd-image-updater-sa.yaml - ServiceAccount argocd-image-updater is valid
/home/manifests/install.yaml - ServiceAccount argocd-image-updater is valid
make: *** [test-manifests] Error 1
```

Modifications made to make the test fail:
```diff
diff --git a/manifests/base/deployment/argocd-image-updater-deployment.yaml b/manifests/base/deployment/argocd-image-updater-deployment.yaml
index 5a38be1..7a11376 100644
--- a/manifests/base/deployment/argocd-image-updater-deployment.yaml
+++ b/manifests/base/deployment/argocd-image-updater-deployment.yaml
@@ -7,7 +7,7 @@ metadata:
     app.kubernetes.io/component: controller
   name: argocd-image-updater
 spec:
-  selector:
+  selectorr:
    matchLabels:
     app.kubernetes.io/name: argocd-image-updater
   strategy:
diff --git a/manifests/install.yaml b/manifests/install.yaml
index 39282cb..000e255 100644
--- a/manifests/install.yaml
+++ b/manifests/install.yaml
@@ -238,7 +238,7 @@ spec:
         name: ssh-known-hosts
       - configMap:
           name: argocd-image-updater-ssh-config
-          optional: true
+            optional: true
         name: ssh-config
       - name: ssh-signing-key
         secret:
```

**Comment by bpsoos** [comment]
@chengfang 
> How about running the script directly in github actions workflow, without building or running images? For local run, we can require users to install kubeconform before running.

Okay, I can make these modifications

**Review by chengfang — APPROVED** [review]

**Comment by bpsoos** [comment]
@chengfang what do you think about this version?

also, in CI this what it looks like now if a manifest is incorrect: https://github.com/argoproj-labs/argocd-image-updater/actions/runs/9701702056/job/26775909356

**Review by chengfang — APPROVED** [review]
LGTM

**Comment by chengfang** [comment]
@bpsoos thanks!

**Pull request merged**
