### PR TITLE
fix: support ocischema.DeserializedImageIndex in registry client

### PR DESCRIPTION
**Pull request by jessebye**
Copies the logic from `manifestlist.DeserializedManifestList` to also handle `ocischema.DeserializedImageIndex` (which ECR returns for certain types of images).

### CODE REVIEW

**Comment by jessebye** [comment]
@jannfis if you have a moment to review, this resolves an issue with using ECR and ARM64 images.

**Comment by jannfis** [comment]
Thank you @jessebye , appreciate that you are tackling this. I'm not sure if I'm good with all that duplicated code. 

Would you think it's possible to come up with code that's not as redundant?

**Comment by jessebye** [comment]
@jannfis I was not happy with that either. I think it could be refactored a bit to eliminate the duplication. Also I think there is a bug, it was updating one parameter but not pinning the digest correctly - seems there may be another place I need to update for it to work. I'll take another look and let you know when it's ready for review!

**Comment by jessebye** [comment]
botched the commits, going to start a fresh branch + PR for this

**Pull request closed without merging**
